[project]
name = "calc"
version = "0.2.0"
description = "A simple python calculator scripting language"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Jeel Dobariya", email = "jeeldobariya38@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
standard = [
    "colorama>=0.4.6",
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
